server:
  port: 8283

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

client:
  ms-country:
    endpoint: http://localhost:8080
